### ISSUE TITLE
Create level managment system.

### ISSUE THREAD

**Issue by RippeR37** [michlord/team-project-2014#19]
Create system to manage levels. Including:

- Tile class
- Decoration class
- Level class
- LevelManager class

**Comment by michlord** [comment]
To access assets (e.g. for creating tile sprites) you could use `Core::frameContext.assetsManager` which is a `unique_ptr` to a global asset manager. Don't forget to `#include <EngineApp/FrameContext.h>`.

**Comment by RippeR37** [comment]
Task completed. Level is now fully implemented with:
- tiles
- decorations
- entities
