### ISSUE TITLE
Improve collision performance

### ISSUE THREAD

**Issue by krabex** [michlord/team-project-2014#43]
Don't check collision with all tiles

**Comment by RippeR37** [comment]
Simple way to do this is to get all the tiles which player occupy and then check each if is empty or brick. If brick then move outside of that brick.

Pseudo-code:

    Stack tiles
    for each corner in Player's bounding box
          Point p = cornerPosition
          Point t = floor(p / tileSize); //tileSize is 32.0f for now
          tiles.push(t); // doesnt add if tile (point) already is added

    for each tile in tiles
          if(Level.getTiles()[tile.y][tile.x].getType) == Type::Brick)
               movePlayer(outsideTile(tile))

Works in constant time :)

**Comment by michlord** [comment]
I wanna do it!!!!

**Comment by michlord** [comment]
If you wan't to alter the existing level collision procedures then you only need to replace
`auto tiles = getTiles()` with something that returns only a subset of tiles that are occupied by the player.
