### ISSUE TITLE
Bad performance on large levels

### ISSUE THREAD

**Issue by michlord** [michlord/team-project-2014#50]
The performance is bad when there are many tiles (about 20000).
This is because we always try to draw all of them even if they don't fit on the screen.

Do something similar to what you did to improve collision detection performance (only draw tiles that are in camera's sight).

**Comment by RippeR37** [comment]
Problem should be fixed. Decorations are still drawn all the time since they can affect camera in more complex way and there are not many decorations for now.

Big level (level1.bmp) included as asset to test it for yourself (**spoilers!!**: this level contains easter eggs!).
