### ISSUE TITLE
Fix crash when closing application.

### ISSUE THREAD

**Issue by RippeR37** [michlord/team-project-2014#58]
If gameplay scene unregister its entities in destructor, crash appears when you try to close application.

**Comment by krabex** [comment]
When game is closing <b>Gameplay</b> destructor is called. 
```C++
Gameplay::~Gameplay() {
    Entity::EntityManager::getInstance().unregisterEntity(player.get());
    Entity::EntityManager::getInstance().unregisterEntity(hud.get());
    [...]
```
For some reason (still unknown for me) when entities are unregistered <b>EntityManager::unregisterEntity</b> makes access violation. Does anyone have any ideas?

**Comment by michlord** [comment]
I am investigating this right now. It seems that the issue might be similar to what happened when changing levels.

**Comment by michlord** [comment]
The problem was that the static instance destructor was called before gameplay destructor.
