### ISSUE TITLE
Fix crash when adding entities (like Knight) to other levels.

### ISSUE THREAD

**Issue by RippeR37** [michlord/team-project-2014#59]

**Comment by krabex** [comment]
Adding entities wasn't the reason why game was crashing. Take a look at Entity::Door::handleMessage():
```c++
            Core::frameContext.sceneStack->popScene();
            Core::frameContext.sceneStack->pushScene(new    Scene::Gameplay(frameContext.sceneStack.get(),
                                                     Level::levelManager.getCurrentID() + 1));
```
<b>sceneStack->popScene()</b> doesn't work immediately so we were creating <b>Scene::Gameplay</b> before we deleted old one. In gameplay constructor we registered entities then they were unregistered in old level destructor. 
To solve this problem I added initializing gameplay not in constructor but in first call of <b>Gameplay::fixedUpdate()</b>.
If someone has got better solution please commit.
